/* Resolution of the three reading sources the canvas offers.
 *
 *   session   — Markdown produced during this session:
 *               the document set the agent asked the reader to review +
 *               host artifacts (plan.md, files/**) + agent-written files +
 *               inline documents pushed through the `show_markdown` action.
 *   workspace — the session workspace root, browsed as a SkimDown folder tree.
 *   path      — any file or folder the agent/user points at.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { scan, buildTree, buildRecentList, statSafe, isMarkdownFile, toPosix } from "./scanner.mjs";
import { sessionArtifactsDir } from "./paths.mjs";
import { loadRegistry } from "./sessionDocs.mjs";

export const SOURCE_SESSION = "session";
export const SOURCE_WORKSPACE = "workspace";
export const SOURCE_PATH = "path";

/** Max bytes read for a single Markdown document. */
const MAX_DOC_BYTES = 8 * 1024 * 1024;

/**
 * Describe which sources are currently available so the shell can render the
 * source picker without guessing.
 */
export async function describeSources(ctx) {
    const artifacts = sessionArtifactsDir(ctx.sessionId);
    const hasArtifacts = Boolean(await statSafe(artifacts));
    return [
        {
            id: SOURCE_SESSION,
            label: "This session",
            detail: hasArtifacts ? artifacts : "Markdown generated by the agent",
            available: true,
        },
        {
            id: SOURCE_WORKSPACE,
            label: "Workspace",
            detail: ctx.workspacePath || "(no workspace)",
            available: Boolean(ctx.workspacePath),
        },
        {
            id: SOURCE_PATH,
            label: "Open path",
            detail: "Any file or folder",
            available: true,
        },
    ];
}

/**
 * Build the sidebar payload for a source.
 * Returns `{ source, root, rootLabel, mode, groups?, tree?, recent?, count }`.
 */
export async function listSource(ctx, source, rootOverride) {
    if (source === SOURCE_SESSION) return listSessionSource(ctx);

    const root = source === SOURCE_WORKSPACE ? ctx.workspacePath : rootOverride;
    if (!root) {
        return {
            source,
            root: null,
            rootLabel: source === SOURCE_WORKSPACE ? "(no workspace)" : "(no path selected)",
            mode: "folder",
            tree: [],
            recent: [],
            count: 0,
        };
    }

    const files = await scan(root);
    return {
        source,
        root,
        rootLabel: path.basename(root) || root,
        mode: "folder",
        tree: buildTree(files),
        recent: buildRecentList(files),
        count: files.length,
    };
}

/**
 * The session source has no single root, so it is presented as grouped,
 * newest-first lists rather than a tree.
 */
async function listSessionSource(ctx) {
    const registry = await loadRegistry(ctx.sessionId);
    const artifactsRoot = sessionArtifactsDir(ctx.sessionId);

    const setEntries = await resolveDocSetEntries(ctx, registry);
    // A set member must not reappear in another group, or the same document
    // would be listed twice.
    const setPaths = new Set(
        setEntries.filter((entry) => entry.type === "file").map((entry) => entry.path.toLowerCase()),
    );
    const setInlineIds = new Set(
        setEntries.filter((entry) => entry.type === "inline").map((entry) => entry.id),
    );

    const artifactFiles = await scan(artifactsRoot);
    const allArtifacts = artifactFiles
        .map((file) => ({
            type: "file",
            kind: file.relPath.startsWith("checkpoints/") ? "checkpoint" : "artifact",
            name: file.name,
            path: file.path,
            relPath: file.relPath,
            folder: file.relPath.includes("/")
                ? file.relPath.slice(0, file.relPath.lastIndexOf("/"))
                : "",
            mtimeMs: file.mtimeMs,
        }))
        .sort((a, b) => b.mtimeMs - a.mtimeMs);

    const artifactEntries = allArtifacts.filter(
        (entry) => entry.kind === "artifact" && !setPaths.has(entry.path.toLowerCase()),
    );
    const checkpointEntries = allArtifacts.filter(
        (entry) => entry.kind === "checkpoint" && !setPaths.has(entry.path.toLowerCase()),
    );

    // Artifact paths must not reappear in the touched group, or the same
    // document would be listed twice.
    const artifactPaths = new Set(allArtifacts.map((entry) => entry.path.toLowerCase()));
    const touchedEntries = [];
    for (const entry of registry.touchedFiles) {
        const lower = entry.path.toLowerCase();
        if (artifactPaths.has(lower) || setPaths.has(lower)) continue;
        const meta = await statSafe(entry.path);
        if (!meta || !meta.isFile()) continue;
        touchedEntries.push({
            type: "file",
            kind: "touched",
            name: path.basename(entry.path),
            path: entry.path,
            relPath: relativeToWorkspace(ctx.workspacePath, entry.path),
            folder: folderLabel(ctx.workspacePath, entry.path),
            mtimeMs: meta.mtimeMs,
            touchedAt: entry.at,
        });
    }
    touchedEntries.sort((a, b) => b.touchedAt - a.touchedAt);

    const inlineEntries = registry.inlineDocs
        .filter((doc) => !setInlineIds.has(doc.id))
        .map((doc) => ({
            type: "inline",
            kind: "inline",
            id: doc.id,
            name: doc.title,
            relPath: doc.id,
            folder: "",
            mtimeMs: doc.updatedAt,
        }));

    const groups = [
        {
            id: "set",
            label: registry.docSet ? registry.docSet.title : "",
            entries: setEntries,
            showTime: false,
        },
        { id: "inline", label: "Markdown displayed by the agent", entries: inlineEntries },
        { id: "artifact", label: "Session artifacts", entries: artifactEntries },
        { id: "touched", label: "Files edited in this session", entries: touchedEntries },
        { id: "checkpoint", label: "Checkpoints", entries: checkpointEntries },
    ].filter((group) => group.entries.length > 0);

    const count = groups.reduce((sum, group) => sum + group.entries.length, 0);

    return {
        source: SOURCE_SESSION,
        root: null,
        rootLabel: "This session",
        mode: "session",
        groups,
        artifactsRoot,
        count,
    };
}

/**
 * Resolve the session's document set into sidebar entries, in the order the
 * agent supplied. Members whose file disappeared or whose inline body was
 * evicted are dropped so the sidebar and the reading order stay in step.
 */
export async function resolveDocSetEntries(ctx, registry) {
    const current = registry || (await loadRegistry(ctx.sessionId));
    const docSet = current.docSet;
    if (!docSet) return [];

    const entries = [];
    for (const item of docSet.items) {
        if (item.kind === "inline") {
            const doc = current.inlineDocs.find((candidate) => candidate.id === item.id);
            if (!doc) continue;
            entries.push({
                type: "inline",
                kind: "set",
                id: doc.id,
                name: item.title || doc.title,
                relPath: doc.id,
                folder: item.description,
                mtimeMs: doc.updatedAt,
            });
            continue;
        }

        const meta = await statSafe(item.path);
        if (!meta || !meta.isFile() || !isMarkdownFile(item.path)) continue;
        entries.push({
            type: "file",
            kind: "set",
            name: item.title || path.basename(item.path),
            path: item.path,
            relPath: relativeToWorkspace(ctx.workspacePath, item.path),
            folder: item.description || folderLabel(ctx.workspacePath, item.path),
            mtimeMs: meta.mtimeMs,
        });
    }
    return entries;
}

function relativeToWorkspace(workspacePath, target) {
    if (!workspacePath) return target;
    const rel = path.relative(workspacePath, target);
    if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) return target;
    return toPosix(rel);
}

function folderLabel(workspacePath, target) {
    const rel = relativeToWorkspace(workspacePath, target);
    if (rel === target) return shortenDir(path.dirname(target));
    return rel.includes("/") ? rel.slice(0, rel.lastIndexOf("/")) : "";
}

/* Files outside the workspace would otherwise show a full absolute path in the
 * sidebar meta column, which crowds out the file name. The last couple of
 * segments are enough to tell two same-named files apart. */
function shortenDir(dir) {
    const parts = toPosix(dir).split("/").filter(Boolean);
    if (parts.length <= 2) return toPosix(dir);
    return `…/${parts.slice(-2).join("/")}`;
}

/** Read a Markdown document off disk, guarding size and encoding. */
export async function readMarkdownFile(absPath) {
    const meta = await statSafe(absPath);
    if (!meta || !meta.isFile()) {
        throw Object.assign(new Error(`Markdown file not found: ${absPath}`), { code: "not_found" });
    }
    if (!isMarkdownFile(absPath)) {
        throw Object.assign(new Error(`Not a Markdown file: ${absPath}`), { code: "not_markdown" });
    }
    if (meta.size > MAX_DOC_BYTES) {
        throw Object.assign(new Error(`Markdown file too large: ${absPath}`), { code: "too_large" });
    }
    const raw = await fs.readFile(absPath, "utf8");
    return {
        markdown: stripBom(raw),
        mtimeMs: meta.mtimeMs,
        size: meta.size,
    };
}

function stripBom(text) {
    return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

/**
 * Classify a user/agent supplied path so `open_path` can pick folder vs file
 * mode without the caller having to know. Relative paths resolve against
 * `baseDir` (the workspace root) rather than the extension host's cwd, which
 * is `$COPILOT_HOME` and never what the caller meant.
 */
export async function classifyPath(target, baseDir) {
    if (typeof target !== "string" || target.trim().length === 0) {
        return { kind: "invalid", reason: "Path is empty" };
    }
    const trimmed = target.trim();
    const resolved = path.isAbsolute(trimmed)
        ? path.resolve(trimmed)
        : path.resolve(baseDir || process.cwd(), trimmed);
    const meta = await statSafe(resolved);
    if (!meta) return { kind: "missing", path: resolved };
    if (meta.isDirectory()) return { kind: "folder", path: resolved };
    if (meta.isFile() && isMarkdownFile(resolved)) return { kind: "file", path: resolved };
    return { kind: "unsupported", path: resolved };
}
